node_movement:
  ros__parameters:
    COXA_LENGTH: 0.050
    FEMUR_LENGTH: 0.063
    TIBIA_LENGTH: 0.099
    COXA_HEIGHT: 0.045


################################
# Coordinate system body

#    ▲ x
#    │
#    │
#   (•)─────▶ y
#      z


################################
# Coordinate system leg
#            z
# y <─────(x)
#          |
#          |
#          ▼ x
#          


    LEG_NAMES: ['RightFront', 'RightMid', 'RightBack', 'LeftFront', 'LeftMid', 'LeftBack']
    CENTER_TO_COXA_X: [-0.109, 0.0, 0.109, -0.109, 0.0, 0.109]

    # orginal
    # CENTER_TO_COXA_Y: [0.068, 0.088, 0.068, 0.068, 0.088, 0.068]
    # OFFSET_COXA_ANGLE_DEG: [-45.0, 0.0, 45.0, -45.0, 0.0, 45.0]
    
    # right changed
    # CENTER_TO_COXA_Y: [-0.068, -0.088, -0.068, 0.068, 0.088, 0.068]
    # OFFSET_COXA_ANGLE_DEG: [-135.0, 180.0, 135.0, -45.0, 0.0, 45.0]

    CENTER_TO_COXA_Y:      [-0.068, -0.088, -0.068, 0.068, 0.088, 0.068]
    OFFSET_COXA_ANGLE_DEG: [-135.0,  -90.0,  -45.0, 135.0,  90.0,  45.0] 


    # sin(45°) and cos(45°) = 0.7071

    # Initial foot positions
    # RightFront:	angles: 0°, 2.3°, 7.7°	| x: 0.092, y: 0.092, z: -0.050
    # RightMid:  	angles: 0°, 2.3°, 7.6°	| x: 0.000, y: 0.130, z: -0.050
    INIT_FOOT_POS_X: [-0.092,    0.0,  0.092, -0.092,    0.0,  0.092]
    INIT_FOOT_POS_Y: [-0.092, -0.130, -0.092,  0.092,  0.130,  0.092]
    INIT_FOOT_POS_Z: [-0.050, -0.050, -0.050, -0.050, -0.050, -0.050]

    # Reference foot positions for standing
    # RightFront:	angles: 0°, 2.3°, 7.7°	| x: 0.092, y: 0.092, z: -0.050
    # RightMid:  	angles: 0°, 2.3°, 7.6°	| x: 0.000, y: 0.130, z: -0.050
    STANDING_FOOT_POS_X: [-0.092,    0.0,  0.092, -0.092,    0.0,  0.092]
    STANDING_FOOT_POS_Y: [-0.092, -0.130, -0.092,  0.092,  0.130,  0.092]
    STANDING_FOOT_POS_Z: [-0.050, -0.050, -0.050, -0.050, -0.050, -0.050]

    # Reference foot positions for lay down
    # angles: 0°, 70°, -55°	| x: 0.0, y: 0.097, z: 0.0086  # original
    # angles: 0°, 71°, -53°	| x: 0.0, y: 0.10, z: 0.01 # new
    LAYDOWN_FOOT_POS_X: [-0.071,  0.000,  0.071, -0.071, 0.000, 0.071]
    LAYDOWN_FOOT_POS_Y: [-0.071, -0.100, -0.071,  0.071, 0.100, 0.071]
    LAYDOWN_FOOT_POS_Z: [ 0.010,  0.010,  0.010,  0.010, 0.010, 0.010]

    # for gaits
    LEG_LIFT_HEIGHT: 0.03      # [m]   // -0.05 + 0.03 = -0.01
    GAIT_STEP_LENGTH: 0.025    # [m]
    FACTOR_VELOCITY_TO_GAIT_CYCLE_TIME: 30.0      # [s²/m] ??

    BODY_MAX_ROLL: 20.0  # deg
    BODY_MAX_PITCH: 20.0 # deg
    BODY_MAX_YAW: 20.0   # deg

    HEAD_MAX_YAW: 30.0
    HEAD_MAX_PITCH: 20.0

