node_communication:
  ros__parameters:
    robot_names: ["spider", "robot", "jamie", "two", "to me", "nikita", "rumbler"]
    vosk/model: vosk-model-small-en-us-0.15
    vosk/sample_rate: 16000
    vosk/blocksize: 2000
